# Generated by Django 4.2.1 on 2023-07-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="garmin_login",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="garmin_password",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
