# Generated by Django 4.2.1 on 2023-07-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0002_alter_dish_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
