# Generated by Django 4.2.1 on 2023-08-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0003_alter_meal_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={},
        ),
        migrations.AlterField(
            model_name="meal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
