# Generated by Django 4.2.1 on 2023-08-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0004_alter_meal_options_alter_meal_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
