# Generated by Django 4.2.1 on 2023-08-04 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0005_alter_meal_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meal",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="meal",
            name="date_time",
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 4, 7, 12, 30, 104634)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="meal",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
