# Generated by Django 4.2.1 on 2023-07-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ButtonText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(choices=[], max_length=255, unique=True)),
                ("text", models.TextField(max_length=5000)),
            ],
            options={
                "db_table": "button_text_table",
            },
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("start_first_time", "start_first_time"),
                            ("start_not_first_time", "start_not_first_time"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("text", models.TextField(max_length=5000)),
            ],
            options={
                "db_table": "text_table",
            },
        ),
    ]
