# Generated by Django 4.2.1 on 2023-07-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buttontext",
            name="title",
            field=models.CharField(
                choices=[
                    ("addtionals", "addtionals"),
                    ("home", "home"),
                    ("statistics", "statistics"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(
                choices=[
                    ("start_first_time", "start_first_time"),
                    ("today_stat", "today_stat"),
                    ("user_error_message", "user_error_message"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
