# Generated by Django 4.2.1 on 2023-07-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_manager", "0004_alter_buttontext_title_alter_text_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(
                choices=[
                    ("disabled_for_new_users", "disabled_for_new_users"),
                    ("product_stat", "product_stat"),
                    ("specify_date", "specify_date"),
                    ("start_first_time", "start_first_time"),
                    ("statistics", "statistics"),
                    ("today_stat", "today_stat"),
                    ("user_error_message", "user_error_message"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
