# Generated by Django 4.2.1 on 2023-07-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_manager", "0005_alter_text_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buttontext",
            name="title",
            field=models.CharField(
                choices=[
                    ("add_garmin", "add_garmin"),
                    ("addtionals", "addtionals"),
                    ("current_day", "current_day"),
                    ("delete_garmin_credentials", "delete_garmin_credentials"),
                    ("home", "home"),
                    ("next_day", "next_day"),
                    ("previous_day", "previous_day"),
                    ("specify_date", "specify_date"),
                    ("statistics", "statistics"),
                    ("sync_garmin", "sync_garmin"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(
                choices=[
                    ("disabled_for_new_users", "disabled_for_new_users"),
                    ("garmin_invalid_credentials", "garmin_invalid_credentials"),
                    ("garmin_password", "garmin_password"),
                    ("garmin_successfully_added", "garmin_successfully_added"),
                    ("garmin_username", "garmin_username"),
                    ("product_stat", "product_stat"),
                    ("specify_date", "specify_date"),
                    ("start_first_time", "start_first_time"),
                    ("statistics", "statistics"),
                    ("today_stat", "today_stat"),
                    ("user_error_message", "user_error_message"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
