# Generated by Django 4.2.1 on 2023-08-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_manager", "0012_alter_text_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buttontext",
            name="title",
            field=models.CharField(
                choices=[
                    ("add_garmin", "add_garmin"),
                    ("additionals", "additionals"),
                    ("cancel", "cancel"),
                    ("current_day", "current_day"),
                    ("delete_garmin_credentials", "delete_garmin_credentials"),
                    ("delete_meal", "delete_meal"),
                    ("home", "home"),
                    ("next_day", "next_day"),
                    ("previous_day", "previous_day"),
                    ("specify_date", "specify_date"),
                    ("statistics", "statistics"),
                    ("sync_garmin", "sync_garmin"),
                    ("today", "today"),
                    ("tomorrow", "tomorrow"),
                    ("yesterday", "yesterday"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
