TRIAL_SEND_CAPTCHA_ANSWER = "TRIAL_SEND_CAPTCHA_ANSWER"
TRIAL_SEND_CAPTCHA = "TRIAL_SEND_CAPTCHA"

PAYMENT_METHOD = "PAYMENT_METHOD"
PAYMENT_AMOUNT = "PAYMENT_AMOUNT"
PAYMENT_CHECK = "PAYMENT_CHECK"

# profile
PROFILE_MENU = "PROFILE_MENU"
CANCLE_PROFILE = "CANCLE_PROFILE"

# new profile
NEW_PROFILE_SUBMIT = "NEW_PROFILE_SUBMIT"
