GARMIN_USERNAME = "GARMIN_USERNAME"
GARMIN_PASSWORD = "GARMIN_PASSWORD"

CHOOSE_MEAL = "CHOOSE_MEAL"
CHOOSE_MEAL_WEIGHT = "CHOOSE_MEAL_WEIGHT"
CHOOSE_MEAL_DATE = "CHOOSE_MEAL_DATE"

STAT_SPECIFY_DATE = "SPECIFY_DATE"

DELETE_MEAL = "DELETE_MEAL"
